### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by aurora** [ghalfacree/bash-scripts#1]
Hi,

i splitted your script `archivedownload.sh` from this repository (but kept the git history) and moved it to my own repository at: https://github.com/aurora/iadl ... while you are right, that it's probably better to use the official Internet Archive tool, i am just a big fan of simple bash scripts :-), and the script just does what i need. So, i hope that's ok for you and: what license did you intend to use for your handy shell scripts? I would like to add a license file to my repository. For me anything would be ok: BSD, GPL, MIT, whatever ...

Best,
Harald

**Comment by ghalfacree** [comment]
Hi, Harald.

Glad you find it useful! I'm happy for you to use any licence you deem appropriate for your modified version; consider the original to be licensed under the permissive WTFPL.

Cheers,

-Gareth

**Comment by aurora** [comment]
Great, thanks!
